// This function fetches the exotic weapon to catalyst record mapping from github and generates a typescript file from it.
import fetch from "cross-fetch";
import { promises as fs } from "fs";
import path from "path";
import { formatStringForFile } from "../utils";

export default async function generateExoticWeaponToCatalystRecordMapping() {
  const response = await fetch(
    "https://raw.githubusercontent.com/DestinyItemManager/d2-additional-info/master/output/exotic-to-catalyst-record.json"
  );

  const exoticsWithCatalysts = await response.json();

  const fileContents = `
// This file is generated by scripts/generateExoticWeaponToCatalystRecordMapping.ts
// Do not edit it directly.

export const exoticsWithCatalysts: Record<number, number> = ${JSON.stringify(
    exoticsWithCatalysts,
    null,
    2
  ).replace(/['"]+/g, "")};
`;

  const formattedFileContents = formatStringForFile(fileContents);

  const filePath = [
    ".",
    "generation",
    "ExoticWeapons",
    "generated",
    "exotic-weapon-to-catalyst-record-mapping.ts",
  ];

  await fs.writeFile(
    path.resolve(path.join(...filePath)),
    formattedFileContents
  );
}
