import { formatStringForFile } from "@d2e/generation/utils";
import { WeaponStat } from "@d2e/types/WeaponStat";

export const generateWeaponStatMapping = (
  weaponStatItems: WeaponStat[]
): string => {
  const weaponStatIdToWeaponStatMappingString = weaponStatItems.map(
    (weaponStatItem) =>
      `[${weaponStatItem.hash}]: ${JSON.stringify(weaponStatItem, null, 2)},`
  );

  const fileContents = `// This file is generated by the generateWeaponStat.ts script.
	// Do not manually make changes to this file.

	import { WeaponStat } from "@d2e/types/WeaponStat";

	export const WeaponStatIdToWeaponStatMapping: Record<number, WeaponStat> = {
		${weaponStatIdToWeaponStatMappingString.join(" ")}
	}
	`;
  return formatStringForFile(fileContents);
};
